### ISSUE TITLE
Size Issue

### ISSUE THREAD

**Issue by monishagarwal215** [CreativeSDK/android-getting-started-samples#22]
As soon as we integrate this SDK size increases by 12 MB.

Is there any way to reduce the size of apk.

If there is any option to exclude some of features if we dont want, so that size issue is resolved.

Please help.

**Comment by ashryanbeats** [comment]
One good course of action, not limited to just the Creative SDK, is to [split the APK into CPU architectures and do multiple APK releases](http://developer.android.com/google/play/publishing/multiple-apks.html). You may see bigger savings with this approach.

If you need any further help, please reach out to [our help desk](http://help.creativesdk.com)
