### ISSUE TITLE
Apk Size Issue

### ISSUE THREAD

**Issue by mthahaseen** [CreativeSDK/android-getting-started-samples#24]
I have integrated only Image Editor SDK in build.gradle, app size goes from 6MB to 16 MB.
Any option to reduce the size.
Please provide a resolution, I think it's a serious issue.

**Comment by ashryanbeats** [comment]
Please see [this issue](https://github.com/CreativeSDK/android-getting-started-samples/issues/22) for one approach.


If you need any further help, please reach out to [our help desk](http://help.creativesdk.com).
