### ISSUE TITLE
error while using the support library 24.2.1

### ISSUE THREAD

**Issue by dabele91** [CreativeSDK/android-getting-started-samples#26]
I'm using the support library 24.2.1 and receiving the following error:

`No resource found that matches the given name (at 'android:textColorHint' with value '@color/hint_foreground_material_light').
`

The error occurs, because the color is a private color and cannot be used outside the support library.

**Comment by ashryanbeats** [comment]
Thanks for the report.

API 24 is not currently supported by the SDK. We will be releasing an update with API 24 very soon.

**Comment by linhnguyen106** [comment]
@dabele91 did you resolve your problem yet. I face the same once, even with  support library 23.4.0

**Comment by dabele91** [comment]
@linhnguyen106 I didn't find a solution yet. I'm waiting for the next release. To solve your problem with the 23.4.0 library, check your other libraries. Perhaps there is a library with the new support library as a peer dependency.

**Comment by dabele91** [comment]
Hi @ashryanbeats, in the creativesdk release notes is an info that an update with api 24 support is available.

I've tried the update but it doesn't work. I've received the same error. That is because the creativesdk needs the support library 24.0.0 and the newest api 24 support library version is 24.2.1.

Is there a plan to upgrade the support library on your side? Because a downgrade from 24.2.1 to 24.0.0 isn't a solution. Version 24.0.0 contains several bugs and misses a lot of features i need.

**Comment by cristhianescobar** [comment]
Hello @ashryanbeats, I am having similar issues as @dabele91 but using version 25.0.0 of the support library. Is the plan to go up to version 25 out the bat or to do incremental releases?

**Comment by ashryanbeats** [comment]
Hi everyone,

Support for API 24 is now available as of this week with the `v4.8.3` release of the Image Editor.

This repo has been updated with sample code and guide that reflects the latest version of the Image Editor.

API 25 support is in the works. We do not have a target release date for it yet.

**Comment by ashryanbeats** [comment]
The guide I refer to is here:
https://github.com/CreativeSDK/android-getting-started-samples/blob/master/image-editor-ui/guide/image-editor.markdown
