### ISSUE TITLE
Quick Launch option

### ISSUE THREAD

**Issue by linhnguyen106** [CreativeSDK/android-getting-started-samples#28]
@ashryanbeats 
I'm trying to force using only one tool by default (CROP) , by using quick launch option. But the CROP editor only shown after few moment of editor image screen. Is there any way I can direct go to CROP editor without go to main editor activity first ?

**Comment by ashryanbeats** [comment]
This is a new feature released this week with Image Editor `v4.8.3`.

See the docs on the new optional [`quickLaunchTool()`](https://github.com/CreativeSDK/android-getting-started-samples/blob/master/image-editor-ui/guide/image-editor.markdown#options) method.
